### PR TITLE
Strings and Boxed types should be compared using "equals()"

### PR DESCRIPTION
**Pull request by HarisAdzemovic**
This fixes 8 Sonarqube violations of rule S4973:
https://rules.sonarsource.com/java/RSPEC-4973

Sonarcloud violation URL:
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AWpBn7x7o4hEA1R-5PL7&resolved=false&rules=squid%3AS4973&types=BUG

Jira Ticket:
https://issues.apache.org/jira/browse/SLING-8825

### CODE REVIEW

**Comment by rombert** [comment]
@cziegeler  - is this something we should apply?  Or does the JSP engine instead intern String or ensure in some other manner that `equals` calls are not needed?

**Comment by cziegeler** [comment]
I don't know, but this code is pretty old and in use for years - we copied the code from Tomcat in this way. so I assume there is a good reason for using == here.
I wouldn't change it as we don't know the risk. Maybe we should add a comment for sonar so sonar ignores these things

**Comment by HarisAdzemovic** [comment]
Thank you for the input, @cziegeler. As I understand the Sonarcloud documentation, only project maintainers with access to its web interface can set up these rules/exclusions (https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/#ignore-issues) but if I can be of assistance, please let me know!

**Comment by cziegeler** [comment]
Thanks @HarisAdzemovic  - I guess we could mark the lines with a // NOSONAR comment

**Comment by HarisAdzemovic** [comment]
Cool, I was unaware of that Sonarqube mechanism. It's definitely something I can do.
Sorry for the noob question but I'm quite new to contributing to open source projects: Is it preferable to open a new PR to keep the commit history cleaner or to modify this one (including reverting the previous changes) to keep the discussion surrounding the change in one place?

**Comment by cziegeler** [comment]
Good question :) I guess its a matter of taste, I would prefer reopening this one and keep everything in one place

**Comment by HarisAdzemovic** [comment]
I added `//NOSONAR` to 5 more violations in the Parser.java file which was ignored in the original commit as it has comments indicating that the use of the `==` operator is intentional.

**Comment by cziegeler** [comment]
Thanks @HarisAdzemovic for the updated PR

**Pull request merged**
